title: GM User Docs
email: hades785@gmail.com
description: >-
  A collection of user made documentation entries for the GooseMod Discord
  modification.
baseurl: "/Documentation" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hades785
github_username:  hades785

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme
plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
